---
group:
  - name: Nathan Chu
    netid: nwc35
  - name: Cindy Li
    netid: cl2674
  - name: Emil Jiang
    netid: eyj7
pm:
  name: Jonathan Yen
  netid: jfy7
publish: false
title: "The OCaml Scheduling Chatbot"
git-repo: "https://github.com/EmilJiang/cs3110-final-real"
demo-video-url: ""
desc: >
  Our project is a scheduler that uses the OpenAI API to query the user on 
  classes that they may be interested in. Using the results of the user input, 
  a schedule with 4 classes is presented which contains the course titles and 
  descriptions.
